package fr.emse.com.cps2_android_app.fakeData;

import org.json.JSONException;
import org.json.JSONObject;

import java.util.ArrayList;
import java.util.Arrays;

/**
 * Created by julien on 19/01/18.
 */

public class FakeObjectsArray {
    public static ArrayList<JSONObject> fakeObjectsArray() {
        String obj1 = "{\"_id\":{\"$oid\":\"5a5b631a47146f013ec6cf2c\"},\"building\":{\"label\":\"Building\",\"description\":\"The building where the object is located\",\"type\":\"String\",\"value\":\"EF\"},\"floor\":{\"label\":\"Floor\",\"description\":\"The floor where the object is located\",\"type\":\"String\",\"value\":\"1\"},\"room\":{\"label\":\"Room\",\"description\":\"The room where the object is located\",\"type\":\"String\",\"value\":\"1.32\"},\"object_type\":{\"label\":\"Object type\",\"description\":\"The type of the object\",\"type\":\"String\",\"value\":\"Lamp\"},\"object_name\":{\"label\":\"Object name\",\"description\":\"The name of the object\",\"type\":\"String\",\"value\":\"Ceiling Lamp 01\"},\"config\":{\"label\":\"Configuration\",\"description\":\"The set of parameters which define the object behaviour\",\"type\":\"JSON\",\"values\":{\"publishing_mode\":{\"label\":\"Publishing mode\",\"description\":\"The way the object publishes its data\",\"type\":\"String\",\"possible_values\":[\"continuous\",\"on-demand\"],\"value\":\"on-demand\"},\"publishing_period\":{\"label\":\"Publishing period\",\"description\":\"The duration in milliseconds between two batches of data in continuous mode\",\"type\":\"Integer\",\"possible_values\":\"positive\",\"value\":2000},\"response_latency\":{\"label\":\"Response latency\",\"description\":\"The delay in milliseconds between the reception of a request and the sending of the answer\",\"type\":\"Integer\",\"possible_values\":\"positive\",\"value\":0}}},\"fields\":{\"label\":\"Fields\",\"description\":\"A set of fields such as metrics that the object can collect,or a status, etc.\",\"type\":\"JSON\",\"values\":{\"status\":{\"label\":\"Status\",\"description\":\"The status of the lamp (ON/OFF)\",\"type\":\"String\",\"source\":\"system\"}}},\"creation_date\":{\"label\":\"Creation date\",\"description\":\"The date when the object was created\",\"type\":\"String\",\"value\":\"2018-01-14 14:03:06.900112\"},\"last_modified\":{\"label\":\"Last modification date\",\"description\":\"The date when the object was last modified\",\"type\":\"String\",\"value\":\"2018-01-14 14:03:06.908701\"}}";
        JSONObject json1 = null;
        String obj2 = "{\"_id\":{\"$oid\":\"5a6116e747146f66e1dbc598\"},\"building\":{\"label\":\"Building\",\"description\":\"The building where the object is located\",\"type\":\"String\",\"value\":\"EF\"},\"floor\":{\"label\":\"Floor\",\"description\":\"The floor where the object is located\",\"type\":\"String\",\"value\":\"4\"},\"room\":{\"label\":\"Room\",\"description\":\"The room where the object is located\",\"type\":\"String\",\"value\":\"4.21\"},\"object_type\":{\"label\":\"Object type\",\"description\":\"The type of the object\",\"type\":\"String\",\"value\":\"Smoke Detector\"},\"object_name\":{\"label\":\"Object name\",\"description\":\"The name of the object\",\"type\":\"String\",\"value\":\"Corridor smoke detector \"},\"config\":{\"label\":\"Configuration\",\"description\":\"The set of parameters which define the object behaviour\",\"type\":\"JSON\",\"values\":{\"publishing_mode\":{\"label\":\"Publishing mode\",\"description\":\"The way the object publishes its data\",\"type\":\"String\",\"possible_values\":[\"continuous\",\"on-demand\"],\"value\":\"on-demand\"},\"publishing_period\":{\"label\":\"Publishing period\",\"description\":\"The duration in milliseconds between two batches of data in continuous mode\",\"type\":\"Integer\",\"possible_values\":\"positive\",\"value\":2000},\"response_latency\":{\"label\":\"Response latency\",\"description\":\"The delay in milliseconds between the reception of a request and the sending of the answer\",\"type\":\"Integer\",\"possible_values\":\"positive\",\"value\":0}}},\"fields\":{\"label\":\"Fields\",\"description\":\"A set of fields such as metrics that the object can collect,or a status, etc.\",\"type\":\"JSON\",\"values\":{\"status\":{\"label\":\"Status\",\"description\":\"The status of the detector (ON\\/OFF)\",\"type\":\"String\",\"source\":\"system\"}}},\"creation_date\":{\"label\":\"Creation date\",\"description\":\"The date when the object was created\",\"type\":\"String\",\"value\":\"2018-01-18 21:51:35.304104\"},\"last_modified\":{\"label\":\"Last modification date\",\"description\":\"The date when the object was last modified\",\"type\":\"String\",\"value\":\"2018-01-18 21:51:35.358393\"}}";
        JSONObject json2 = null;
        String obj3 = "{\"_id\":{\"$oid\":\"5a6116f547146f66f6b67f95\"},\"building\":{\"label\":\"Building\",\"description\":\"The building where the object is located\",\"type\":\"String\",\"value\":\"EF\"},\"floor\":{\"label\":\"Floor\",\"description\":\"The floor where the object is located\",\"type\":\"String\",\"value\":\"1\"},\"room\":{\"label\":\"Room\",\"description\":\"The room where the object is located\",\"type\":\"String\",\"value\":\"1.32\"},\"object_type\":{\"label\":\"Object type\",\"description\":\"The type of the object\",\"type\":\"String\",\"value\":\"systemData Publisher\"},\"object_name\":{\"label\":\"Object name\",\"description\":\"The name of the object\",\"type\":\"String\",\"value\":\"Computer\"},\"config\":{\"label\":\"Configuration\",\"description\":\"The set of parameters which define the object behaviour\",\"type\":\"JSON\",\"values\":{\"publishing_mode\":{\"label\":\"Publishing mode\",\"description\":\"The way the object publishes its data\",\"type\":\"String\",\"possible_values\":[\"continuous\",\"on-demand\"],\"value\":\"continuous\"},\"publishing_period\":{\"label\":\"Publishing period\",\"description\":\"The duration in milliseconds between two batches of data in continuous mode\",\"type\":\"Integer\",\"possible_values\":\"positive\",\"value\":2000},\"response_latency\":{\"label\":\"Response latency\",\"description\":\"The delay in milliseconds between the reception of a request and the sending of the answer\",\"type\":\"Integer\",\"possible_values\":\"positive\",\"value\":0}}},\"fields\":{\"label\":\"Fields\",\"description\":\"A set of fields such as metrics that the object can collect,or a status, etc.\",\"type\":\"JSON\",\"values\":{\"disk_usage\":{\"label\":\"Disk usage\",\"description\":\"The disk usage in percent\",\"type\":\"Float\",\"source\":\"function\"},\"memory_usage\":{\"label\":\"Memory usage\",\"description\":\"The RAM usage in percent\",\"type\":\"Float\",\"source\":\"function\"},\"cpu_usage\":{\"label\":\"CPU usage\",\"description\":\"The CPU usage in percent\",\"type\":\"Float\",\"source\":\"function\"}}},\"creation_date\":{\"label\":\"Creation date\",\"description\":\"The date when the object was created\",\"type\":\"String\",\"value\":\"2018-01-18 21:51:49.953428\"},\"last_modified\":{\"label\":\"Last modification date\",\"description\":\"The date when the object was last modified\",\"type\":\"String\",\"value\":\"2018-01-18 21:51:49.963102\"}}";
        JSONObject json3 = null;

        try {
            json1 = new JSONObject(obj1);
            json2 = new JSONObject(obj2);
            json3 = new JSONObject(obj3);
        } catch (JSONException e) {
            e.printStackTrace();
        }

        ArrayList<JSONObject> fakeArray = new ArrayList<JSONObject>(
                Arrays.asList(json1, json2, json3)
        );
        return fakeArray;
    }
}
